version: '3'
services:
  db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4305:3305"
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/sinka_school
    ports:
      - 3001:3001
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql-data: